version: '3.5'

services:
  bongo-bot:
    image: ghcr.io/redhawk18/bongo-bot:latest
    env_file:
      - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: ${LAVALINK_PORT}
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
    networks:
      - lavalink
      - postgres
    pull_policy: always
    restart: unless-stopped

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3-alpine
    networks:
      - lavalink
    ports:
      - "2333:2333"
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
       - postgres:/data/postgres

networks:
  lavalink:
  postgres:

volumes:
  pgadmin:
  postgres:
