version: '3.5'

services:
  bongo-bot:
    build: .
    env_file:
      - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_DATABASE: ${POSTGRES_DATABASE}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${POSTGRES_PORT}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: ${LAVALINK_PORT}
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
    networks:
      - lavalink
      - postgres
    restart: unless-stopped
    volumes:
      - ./src/:/app/src
  
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    networks:
      - lavalink
    ports:
      - "2333:2333"
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
       - ./postgres:/data/postgres

networks:
  lavalink:
  postgres:

