
version: '3.5'

services:
  discord-bot:
    image: discord-bot
    env_file:
      - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: ${LAVALINK_PORT}
      LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}
      TROLLED_USER_ID: ${TROLLED_USER_ID}
    networks:
      - lavalink
      - postgres
    restart: unless-stopped

  lavalink:
    image: lavalink
    networks:
      - lavalink
    ports:
      - "2333:2333"
    restart: unless-stopped

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
       - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    logging:
      driver: "none"
    networks:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin

networks:
  lavalink:
  postgres:
  
volumes:
  pgadmin:
  postgres:
