name: docker-build-push

on: 
  push:
    branches:
      - main

jobs:
  docker-build-push:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/redhawk18/bongo-bot:${{ github.sha }}

